export * from "./src/schema/news";
export * from "./src/schema/banners";
export * from "./src/schema/statistics";
export * from "./src/schema/gallery";
export * from "./src/schema/contacts";
export * from "./src/schema/content";
export * from "./src/schema/teachers";
export * from "./src/schema/alumni";
export * from "./src/schema/classrooms";
