uploads = []
outputs = []

[[generated]]
id = "nGvHaLgK5Jt_PCW4mELzd"
uri = "file://artifacts/alberuni/public/images/hero-banner.png"
type = "image"
title = "Grand university campus building"

[[generated]]
id = "oEa_SZMvi32yIiVINNCvy"
uri = "file://artifacts/alberuni/public/images/gallery/aerial.png"
type = "image"
title = "Aerial university campus view"

[[generated]]
id = "GgBn5vzYh0qJYdlHnel3C"
uri = "file://artifacts/alberuni/public/images/about/library.png"
type = "image"
title = "University lecture hall"

[[generated]]
id = "rHG4c62YAFrF078w5VA5C"
uri = "file://artifacts/alberuni/public/images/news/news-1.png"
type = "image"
title = "Academic conference event"

[[generated]]
id = "CewsI_6guJHGr-kL9PC8D"
uri = "file://artifacts/alberuni/public/images/news/news-2.png"
type = "image"
title = "Students collaborating together"

[[generated]]
id = "GXRXJ-p0OT9LwvOM3QKMF"
uri = "file://artifacts/alberuni/public/images/news/news-3.png"
type = "image"
title = "Science laboratory research"
