export * from "./news";
export * from "./banners";
export * from "./statistics";
export * from "./gallery";
export * from "./contacts";
export * from "./content";
export * from "./teachers";
export * from "./alumni";
export * from "./classrooms";
